spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/weatherdb
    username: weather
    password: weatherpass

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/weather"
          jwk-set-uri: "http://keycloak:8080/realms/weather/protocol/openid-connect/certs"

logging:
  level:
    org.springframework.security: DEBUG
